---
- name: "Setting preparatory facts"
  max_fail_percentage: 10
  hosts: pce
  become: true
  tasks:
    # Your preparatory tasks here

- name: "Check PCE cluster makeup and define type"
  hosts: localhost
  gather_facts: false
  vars:
    prefix_name: "MNC1"  # Set the appropriate group name here
  tasks:
    - name: "Checking PCE cluster makeup for type definition"
      run_once: true
      set_fact:
        node_count: "{{ groups[prefix_name] | length }}"

    - name: "Print node count"
      debug:
        msg: "The node count is {{ node_count }}"

    - name: "Set cluster type 2x2 based on group membership counts"
      set_fact: 
        cluster_type: "4node_v0"
      run_once: true
      when: node_count == 4

    - name: "Set cluster type as 4x2 based on group membership counts"
      set_fact:
        cluster_type: "6node_v0"
      run_once: true
      when: node_count == 6

- name: "Running BUILD task"
  max_fail_percentage: 10
  become: true
  hosts: "{{ groups[prefix_name] }}" 
  roles:
    - role: common
    - role: pce-harden
    - role: pce
    - role: pce-prepare