---
- name: "Check PCE cluster makeup and define type"
  hosts: localhost
  gather_facts: false
  vars:
    prefix_name: "MNC1"  # Set the appropriate group name here
  tasks:
    - name: "Checking PCE cluster makeup for type definition"
      run_once: true
      set_fact:
        node_count: "{{ groups[prefix_name] | length }}"

    - name: "Print node count"
      debug:
        msg: "The node count is {{ node_count }}"

    # - name: "Set cluster type 2x2 based on group membership counts"
    #   set_fact: 
    #     cluster_type: "4node_v0"
    #   run_once: true
    #   when: node_count == 4

    # - name: "Set cluster type as 4x2 based on group membership counts"
    #   set_fact:
    #     cluster_type: "6node_v0"
    #   run_once: true
    #   when: node_count == 6


- name: "Set cluster type as 2x2 based on group membership counts"
  hosts: all
  gather_facts: false
  tasks:
    - name: Set cluster_type fact
      set_fact:
        cluster_type: "4node_v0"
      run_once: true
      when: node_count == 4

- name: "Set cluster type as 4x2 based on group membership counts"
  hosts: all
  gather_facts: false
  tasks:
    - name: Set cluster_type fact
      set_fact:
        cluster_type: "6node_v0"
      run_once: true
      when: node_count == 6


- name: "Set node_type fact for each host"
  hosts: all
  gather_facts: false
  tasks:
    - name: Set node_type fact
      set_fact:
        node_type: "{{ item }}"
      with_items: "{{ hostvars[inventory_hostname]['group_names'] }}"
      when: item in ['core0', 'core1', 'core2', 'core3', 'data0', 'data1']


- name: "Set fact variable - node class - core"
  hosts: all
  gather_facts: false
  tasks:
  - name: Set node_class fact
    set_fact:
      node_class: "core"
    when: (item in ["core0","core1","core2","core3"])
    with_items: "{{hostvars[inventory_hostname]['group_names']}}"

 
- name: "Set fact variable - node class - data"
  hosts: all
  gather_facts: false
  tasks:
  - name: Set node_class fact
    set_fact:
      node_class: "{{item}}"
    when: (item in ["data0","data1"])
    with_items: "{{hostvars[inventory_hostname]['group_names']}}"

- name: "Running BUILD task"
  max_fail_percentage: 10
  become: true
  remote_user: root
  hosts: "{{ groups[prefix_name] }}" 
  vars:
    prefix_name: "MNC1"  # Pass the variable again
    cluster_type: {{cluster_type}}
  roles:
    - role: common
    - role: pce-harden
    - role: pce
    - role: pce-prepare
