---
#- name:  Uninstall VEN
#- name:  Display VEN results
#- name:  Check iptables
#- name:  Display iptables results
- name: "Check for and install dependencies"
  yum:
    state: present
    name: ["coreutils","findutils","net-tools","procps","gawk","grep","util-linux-ng","sed","sudo","glibc","libgcc","libstdc++","ncurses-libs","zlib"]
  when: "prefix_name in group_names"


- name: "Install tools and required packages"
  yum: 
      state: present
      name: ["postfix","logrotate"]
  when: "prefix_name in group_names"


# - name: "Install epel-release for CentOS only"
#   yum: 
#       name: ["epel-release"]
#       state: present
#   ignore_errors: True

- name: "Stop iptables service"
  service:
    name: iptables
    state: stopped
    enabled: false
  ignore_errors: True


- name: "Stop firewalld service" 
  service:
    name: firewalld 
    state: stopped
    enabled: false
  ignore_errors: True

- name: "Disable selinux"
  selinux:
    state: disabled


- name: Stop nftables service
  service:
    name: nftables
      state: stopped


- name: "Configure Alias File"
  blockinfile:
      dest: /etc/profile.d/global_aliases.sh
      create: yes
      block: |
        # Illumio-specific aliases and functions
        alias check="sudo -u ilo-pce /opt/illumio-pce/illumio-pce-env check"
        alias ctl="sudo -u ilo-pce /opt/illumio-pce/illumio-pce-ctl"
        alias db="sudo -u ilo-pce /opt/illumio-pce/illumio-pce-db-management"
 


- name: "Copy CA bundle to /etc/pki/ca-trust/source/anchors/"
  copy:
      src: ./roles/common/files/{{ root_ca_cert }}
      dest: /etc/pki/ca-trust/source/anchors/
      mode: 0400
  when: root_ca_cert != ''

- name: "update-ca-trust force-enable"
  command: update-ca-trust force-enable
  when: root_ca_cert != ''

- name: "update-ca-trust extract"
  command: update-ca-trust extract
  when: root_ca_cert != ''



