---

- name: "Running illumio-pce-ctl status to check runlevel"
  command: illumio-pce-ctl status -x
  become: true
  become_user: ilo-pce
  register: pce_status
  failed_when:  pce_status.rc > 3
  
  args:
    chdir: /tmp/


- name: "Stopping PCE"
  command: illumio-pce-ctl stop
  become: true
  become_user: ilo-pce
  when: "pce_status.rc != 3 and pce_status.rc != 2  "


- name: "Waiting for PCE to stop"
  command:  illumio-pce-ctl status -w 180
  become: true
  become_user: ilo-pce
  register: pce_status
  until: pce_status.rc == 0
  retries: 0
  when: " pce_status.rc != 3 and pce_status.rc != 2 "
  args:
    chdir: /tmp/


- name: "Uninstall the UI RPM"
  yum:
    name: illumio-pce-ui
    state: absent
  when: " 'corenodes' in group_names "



- name: "Uninstall the PCE RPM"
  #command: rpm -e illumio-pce
  yum:
    name: illumio-pce
    state: absent



- name: "Clean up directories"
  file:
    path: "{{item}}"
    state: absent
  with_items:
   - /var/lib/illumio-pce/
   - /var/log/illumio-pce/
   - /etc/illumio-pce
   - /opt/illumio-pce

