---
- name: Run a command and collect output and return code
  hosts: all
  tasks:
    - name: "Waiting for Cluster Status to reach run-level 5"
      command: illumio-pce-ctl cluster-status
      become: true
      become_user: ilo-pce
      register: result
      until: result.rc == 1
      failed_when: "'status: RUNNING' not in result.stdout or 'runlevel: 5' not in result.stdout"
      # until: result.rc == 1
    # - name: Display command output
    #   debug:
    #     msg: "{{ result.stdout }}"

    - name: Display return code
      debug:
        msg: "Return code: {{ result.rc }}"
