---
- name: Run a command and collect output and return code
  hosts: all
  tasks:
    - name: "Waiting for Cluster Status to reach run-level 5"
      command: illumio-pce-ctl cluster-status
      become: true
      become_user: ilo-pce
      register: result

    # - name: Display command output
    #   debug:
    #     msg: "{{ result.stdout }}"

    - name: Display return code
      debug:
        msg: "Return code: {{ result.rc }}"
