---

# Applies hardening to the PCE nodes to protect PCE related services

- name: "Install IPTables if required"
  yum:
    state: latest
    name: ["iptables","iptables-services","firewalld"]
  when: "prefix_name in group_names"



- name: "Enable conntrack in modprobe"
  modprobe:
    name: nf_conntrack
    state: present
  when: "'corenodes' in group_names"


- name: "Update nf_conntrack_max value"
  shell: echo 1048576 > /proc/sys/net/nf_conntrack_max
  when: "'corenodes' in group_names"


- name: "Update nf_conntrack_hashsize value"
  shell: echo 262144 > /sys/module/nf_conntrack/parameters/hashsize
  when: "'corenodes' in group_names"


# - name: "Update nf_conntrack_max boot value"
#   shell: echo "net.nf_conntrack_max=1048576" > /etc/sysctl.d/illumio.con
#   when: "'corenodes' in group_names"


- name: "Update nf_conntrack_hashsize boot value"
  shell: echo "options nf_conntrack hashsize=262144" > /etc/modprobe.d/illumio.conf
  when: "'corenodes' in group_names"


# - name: "Check for existing IPTables Config"
#   stat: 
#     path: /etc/sysconfig/iptables
#   register: ipt_stat
#   when: "prefix_name in group_names"


# - name: "Check for initial IPTables pipgen backup"
#   stat:
#     path: /etc/sysconfig/iptables.pipgen.orig
#   register: ipt_pipgen_stat
#   when: "prefix_name in group_names"


# - name: "Backup original IPTables Config"
#   command: mv /etc/sysconfig/iptables /etc/sysconfig/iptables.pipgen.orig
#   when: "prefix_name in group_names and ipt_stat.stat.exists and ipt_pipgen_stat.stat.exists == false"


# - name: "Insert pipgen firewall"
#   command: cp /var/tmp/illumio-pipgen/iptables /etc/sysconfig/iptables
#   when: "prefix_name in group_names"


# - name: "Clean up pipgen temp directory"
#   file:
#     path: /var/tmp/illumio-pipgen/
#     state: absent
#   when: "prefix_name in group_names" 


# - name: "Restart IP Tables and apply pipgen firewall"
#   systemd:
#     name: iptables
#     state: restarted
#   when: "prefix_name in group_names"




# - name: "Clean up pipgen temp directory"
#   file:
#     path: /tmp/illumio-vpngen/
#     state: absent
#   when: "prefix_name in group_names"
